{"name": "test_dashboard_acesso_autenticado[chrome]", "status": "failed", "statusDetails": {"message": "AssertionError: Should be redirected to dashboard after login\nassert 'dashboard' in 'http://web:8000/accounts/login/'\n +  where 'http://web:8000/accounts/login/' = <selenium.webdriver.remote.webdriver.WebDriver (session=\"3c1c914caa4c269ddd451ca4a077dde6\")>.current_url", "trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/app/tests/dashboard_acesso_autenticado_test.py\", line 27, in test_dashboard_acesso_autenticado\n    assert \"dashboard\" in driver.current_url, \"Should be redirected to dashboard after login\"\nAssertionError: Should be redirected to dashboard after login\nassert 'dashboard' in 'http://web:8000/accounts/login/'\n +  where 'http://web:8000/accounts/login/' = <selenium.webdriver.remote.webdriver.WebDriver (session=\"3c1c914caa4c269ddd451ca4a077dde6\")>.current_url"}, "description": "TP-13: Dashboard - Acesso Autenticado", "steps": [{"name": "Make request to Faker API: http://faker:5000/generate/user", "status": "passed", "start": 1740707391274, "stop": 1740707391279}], "attachments": [{"name": "dashboard_after_login", "source": "5bdd92e4-1f4d-4693-a687-b1ab34001b06-attachment.png", "type": "image/png"}, {"name": "log", "source": "c08df5ff-1cef-4408-bbb7-c2b570eab5e3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "947fc902-dd06-4a29-81ab-8ccd94eac48a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "selenium_browser", "value": "'chrome'"}], "start": 1740707391252, "stop": 1740707392047, "uuid": "a74627c0-fc06-447d-ad18-51a5b83d16dc", "historyId": "591a8561ae07db7825a562d17a8fd33c", "testCaseId": "061acd0a6102e23d187348f4d2fda05c", "fullName": "tests.dashboard_acesso_autenticado_test#test_dashboard_acesso_autenticado", "labels": [{"name": "story", "value": "Authenticated Access"}, {"name": "feature", "value": "Dashboard"}, {"name": "epic", "value": "Authentication"}, {"name": "tag", "value": "function"}, {"name": "tag", "value": "nondestructive"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "dashboard_acesso_autenticado_test"}, {"name": "host", "value": "e130d6c28101"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.dashboard_acesso_autenticado_test"}]}