{"name": "test_dashboard_acesso_nao_autenticado[chrome]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559f6589a0ca <unknown>\n#1 0x559f655662b0 <unknown>\n#2 0x559f655b5b22 <unknown>\n#3 0x559f655b5dc1 <unknown>\n#4 0x559f655fb994 <unknown>\n#5 0x559f655da92d <unknown>\n#6 0x559f655f8e26 <unknown>\n#7 0x559f655da6a3 <unknown>\n#8 0x559f655a84f3 <unknown>\n#9 0x559f655a94fe <unknown>\n#10 0x559f65860d7b <unknown>\n#11 0x559f65864d31 <unknown>\n#12 0x559f6584cc85 <unknown>\n#13 0x559f658658a2 <unknown>\n#14 0x559f65831e1f <unknown>\n#15 0x559f65888e48 <unknown>\n#16 0x559f65889013 <unknown>\n#17 0x559f65898ebc <unknown>\n#18 0x7ff3c68ecac3 <unknown>", "trace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/usr/local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/app/tests/dashboard_acesso_não_autenticado_test.py\", line 39, in test_dashboard_acesso_nao_autenticado\n    dashboard_page.logout()\n  File \"/app/pages/dashboard_page.py\", line 39, in logout\n    self.click_element(*self.locators.navbar.LOGOUT_LINK)\n  File \"/app/pages/base_page.py\", line 57, in click_element\n    element = self.find_clickable_element(*locator, timeout=2)\n  File \"/app/pages/base_page.py\", line 35, in find_clickable_element\n    return self.wait_for_element(locator, timeout, EC.element_to_be_clickable)\n  File \"/app/pages/base_page.py\", line 22, in wait_for_element\n    return wait.until(condition(locator))\n  File \"/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 101, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559f6589a0ca <unknown>\n#1 0x559f655662b0 <unknown>\n#2 0x559f655b5b22 <unknown>\n#3 0x559f655b5dc1 <unknown>\n#4 0x559f655fb994 <unknown>\n#5 0x559f655da92d <unknown>\n#6 0x559f655f8e26 <unknown>\n#7 0x559f655da6a3 <unknown>\n#8 0x559f655a84f3 <unknown>\n#9 0x559f655a94fe <unknown>\n#10 0x559f65860d7b <unknown>\n#11 0x559f65864d31 <unknown>\n#12 0x559f6584cc85 <unknown>\n#13 0x559f658658a2 <unknown>\n#14 0x559f65831e1f <unknown>\n#15 0x559f65888e48 <unknown>\n#16 0x559f65889013 <unknown>\n#17 0x559f65898ebc <unknown>\n#18 0x7ff3c68ecac3 <unknown>"}, "description": "TP-14: Dashboard - Tentativa de Acesso Não Autenticado", "steps": [{"name": "Make request to Faker API: http://faker:5000/generate/user", "status": "passed", "start": 1740707418427, "stop": 1740707418432}], "attachments": [{"name": "dashboard_direct_access_attempt", "source": "4c0d478f-7532-4fc7-86a2-aa0b1c29dba6-attachment.png", "type": "image/png"}, {"name": "dashboard_after_authentication", "source": "3dd8f79e-fb43-4318-a199-2eb7d31847a5-attachment.png", "type": "image/png"}, {"name": "element_not_found", "source": "354c5896-e019-47a5-9b4d-431e3b35616b-attachment.png", "type": "image/png"}, {"name": "click_failed", "source": "df4f4e62-6690-4c56-a3ac-350e8527dd03-attachment.png", "type": "image/png"}, {"name": "log", "source": "42c1b135-17e3-42a0-bf11-715c8937903f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b1dc01b7-8c95-4343-9af7-e2cd8e6a2efb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "selenium_browser", "value": "'chrome'"}], "start": 1740707418427, "stop": 1740707430023, "uuid": "b44124d6-c2d2-4e29-a8cf-32781352c5f5", "historyId": "c2275a8979a5b604bd1438c9dec7cd21", "testCaseId": "f38e5ec0e1f594153ff890aac1349ba0", "fullName": "tests.dashboard_acesso_não_autenticado_test#test_dashboard_acesso_nao_autenticado", "labels": [{"name": "story", "value": "Unauthorized Access"}, {"name": "feature", "value": "Dashboard"}, {"name": "epic", "value": "Authentication"}, {"name": "tag", "value": "security"}, {"name": "tag", "value": "nondestructive"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "dashboard_acesso_não_autenticado_test"}, {"name": "host", "value": "e130d6c28101"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.dashboard_acesso_não_autenticado_test"}]}